"""JobRepository (MASTER_PLAN 10.6).

``jobs.id`` is an application-generated UUIDv7 (D-013); ``create`` therefore
accepts a pre-built ``Job`` whose ``id`` was assigned by ``core.uuid7``.
"""

from __future__ import annotations

import datetime
import uuid

from sqlalchemy import select, update

from infrastructure.database.models import Job
from infrastructure.database.repositories.base import SqlAlchemyRepository


class JobRepository(SqlAlchemyRepository[Job]):
    model = Job

    async def get_by_uuid(self, job_id: uuid.UUID) -> Job | None:
        result = await self.session.execute(select(Job).where(Job.id == job_id))
        return result.scalar_one_or_none()

    async def create(
        self,
        *,
        job_id: uuid.UUID,
        user_id: int,
        media_id: int,
        format_: str,
        quality: str,
        priority: int,
        correlation_id: uuid.UUID | None,
        status: str,
    ) -> Job:
        """Insert a job whose id was generated by ``core.uuid7`` (D-013)."""
        job = Job(
            id=job_id,
            user_id=user_id,
            media_id=media_id,
            format=format_,
            quality=quality,
            priority=priority,
            correlation_id=correlation_id,
            status=status,
        )
        return await self.add(job)

    async def set_status(
        self,
        job_id: uuid.UUID,
        status: str,
        *,
        started_at: datetime.datetime | None = None,
        finished_at: datetime.datetime | None = None,
        error_message: str | None = None,
        increment_retry: bool = False,
    ) -> None:
        """Advance the job state machine (Section 12.3) by id."""
        values: dict[str, object] = {"status": status}
        if started_at is not None:
            values["started_at"] = started_at
        if finished_at is not None:
            values["finished_at"] = finished_at
        if error_message is not None:
            values["error_message"] = error_message
        if increment_retry:
            values["retry_count"] = Job.retry_count + 1
        await self.session.execute(update(Job).where(Job.id == job_id).values(**values))
        await self.session.flush()
