"""JobRepository (MASTER_PLAN 10.6).

``jobs.id`` is an application-generated UUIDv7 (D-013); ``create`` therefore
accepts a pre-built ``Job`` whose ``id`` was assigned by ``core.uuid7``.
"""

from __future__ import annotations

import datetime
import uuid
from collections.abc import Sequence

from sqlalchemy import func, select, update

from domain.enums import JobStatus
from infrastructure.database.models import Job
from infrastructure.database.repositories.base import SqlAlchemyRepository

# Non-terminal states: a job in any of these is still "in flight" for its owner.
_ACTIVE_STATUSES = tuple(s.value for s in JobStatus if not s.is_terminal)

# States that mean "a worker had dequeued and claimed this job". If that worker dies
# (crash / restart / OOM), the job is stranded here forever — it is no longer in the
# Redis queue, so nothing re-drives it, and its active_downloads row keeps blocking
# every retry for the same (media, format, quality) with "already being prepared".
# QUEUED / RETRY_QUEUED are intentionally excluded: those still live in the durable
# (AOF) Redis queue and get reprocessed normally after a restart.
_RECLAIMABLE_STATUSES = (JobStatus.PROCESSING.value,)


class JobRepository(SqlAlchemyRepository[Job]):
    model = Job

    async def get_by_uuid(self, job_id: uuid.UUID) -> Job | None:
        result = await self.session.execute(select(Job).where(Job.id == job_id))
        return result.scalar_one_or_none()

    async def count_active_for_user(
        self, user_id: int, *, within_seconds: int | None = None
    ) -> int:
        """Count this user's in-flight (non-terminal) jobs (free single-active cap, #16).

        ``within_seconds`` bounds the window to *recent* jobs so a job stuck in a
        non-terminal state (worker down or crashed, before the Sprint-10 reaper exists)
        ages out and stops blocking the user (#24). A job older than the window is
        treated as dead for capping purposes.
        """
        conditions = [Job.user_id == user_id, Job.status.in_(_ACTIVE_STATUSES)]
        if within_seconds is not None:
            cutoff = datetime.datetime.now(datetime.UTC) - datetime.timedelta(
                seconds=within_seconds
            )
            conditions.append(Job.created_at > cutoff)
        result = await self.session.execute(
            select(func.count()).select_from(Job).where(*conditions)
        )
        return int(result.scalar_one())

    async def fail_stalled_inflight(
        self,
        *,
        older_than_seconds: float | None = None,
        error: str = "reclaimed: worker/process restart",
    ) -> int:
        """Fail jobs a dead worker left stranded in ``PROCESSING`` and return the count.

        Marking them ``PERMANENTLY_FAILED`` (terminal) lets the existing orphan sweeps
        drop their ``active_downloads`` / ``job_waiters``, so retries stop hitting
        "already being prepared".

        ``older_than_seconds=None`` reaps *all* claimed jobs — safe **only at process
        startup**, before any worker begins claiming new jobs, since nothing is running
        yet. A positive value reaps only jobs whose work began before the cutoff: a
        periodic backstop for a hang without a restart that must never touch a
        still-running download.
        """
        conditions = [Job.status.in_(_RECLAIMABLE_STATUSES)]
        if older_than_seconds is not None:
            cutoff = datetime.datetime.now(datetime.UTC) - datetime.timedelta(
                seconds=older_than_seconds
            )
            conditions.append(func.coalesce(Job.started_at, Job.created_at) < cutoff)
        now = datetime.datetime.now(datetime.UTC)
        result = await self.session.execute(
            update(Job)
            .where(*conditions)
            .values(
                status=JobStatus.PERMANENTLY_FAILED.value,
                error_message=error,
                finished_at=now,
            )
        )
        await self.session.flush()
        return int(result.rowcount)

    async def list_recent(
        self, *, limit: int = 50, offset: int = 0, status: str | None = None
    ) -> Sequence[Job]:
        """Most-recent jobs first for the admin ``/v1/admin/jobs`` surface (Task 8.3).

        Optionally filtered by ``status``. Ordered by ``created_at`` DESC (the partition
        key), with ``id`` as a stable tiebreak.
        """
        stmt = select(Job)
        if status is not None:
            stmt = stmt.where(Job.status == status)
        stmt = stmt.order_by(Job.created_at.desc(), Job.id).limit(limit).offset(offset)
        result = await self.session.execute(stmt)
        return result.scalars().all()

    async def create(
        self,
        *,
        job_id: uuid.UUID,
        user_id: int,
        media_id: int,
        format_: str,
        quality: str,
        priority: int,
        correlation_id: uuid.UUID | None,
        status: str,
    ) -> Job:
        """Insert a job whose id was generated by ``core.uuid7`` (D-013)."""
        job = Job(
            id=job_id,
            user_id=user_id,
            media_id=media_id,
            format=format_,
            quality=quality,
            priority=priority,
            correlation_id=correlation_id,
            status=status,
        )
        return await self.add(job)

    async def set_status(
        self,
        job_id: uuid.UUID,
        status: str,
        *,
        started_at: datetime.datetime | None = None,
        finished_at: datetime.datetime | None = None,
        error_message: str | None = None,
        increment_retry: bool = False,
    ) -> None:
        """Advance the job state machine (Section 12.3) by id."""
        values: dict[str, object] = {"status": status}
        if started_at is not None:
            values["started_at"] = started_at
        if finished_at is not None:
            values["finished_at"] = finished_at
        if error_message is not None:
            values["error_message"] = error_message
        if increment_retry:
            values["retry_count"] = Job.retry_count + 1
        await self.session.execute(update(Job).where(Job.id == job_id).values(**values))
        await self.session.flush()
